### ISSUE TITLE
Extending Vehicle Class

### ISSUE THREAD

**Issue by Tyldo** [slehmann36/OpenSource_AssessmentTwo#14]
Extending the vehicle class to show when the vehicle was last serviced, print the total revenue, and distance since the last service

**Comment by Tyldo** [comment]
u da boss

**Comment by Tyldo** [comment]
@slehmann36 help

**Comment by joshrawson** [comment]
help me first

**Comment by Tyldo** [comment]
@slehmann36 @slehmann36 @slehmann36
